name: K6 load test
on: [push]
permissions:
  contents: write
jobs:
  build: 
    name: K6 load test
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4

      - name: Step 2 - Run k6 Load Test
        uses: grafana/k6-action@v0.2.0
        with: 
          filename: scripts/aula31.js  # Ajuste para o caminho correto se necessário

      - name: Step 3 - Create Report Directory
        run: |
          mkdir -p report
          mv index.html report || echo "index.html not found"  # Move o relatório gerado ou exibe mensagem

      - name: Step 4 - Upload Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: relatorio de testes de performance
          path: report
      
      - name: Step 5 - Publish Report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: report
