name: K6 load test
on: [push]
permissions:
  contents: write
jobs:
  build: 
    name: K6 load test
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v4

      - name: step 2 - run k6 load test
        uses: grafana/k6-action@v0.2.0
        with: 
          filename: aula31.js

      - run: ls && mkdir report && mv index.html report   # Verifica se index.html é gerado
      
      - name: step 3 - upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: relatorio de testes de performance
          path: report
      
      - name: step 4 - publish report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: report
