name: K6 load test

on: [push]

permissions:
  contents: write

jobs:
  build:
    name: K6 load test

    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4

      - name: Step 2 - Run k6 Load Test
        run: |
          mkdir -p logs
          echo "Iniciando a execução do K6 com Dashboard e Relatório HTML..."

          # Definindo as variáveis de ambiente para o Dashboard do K6
          export K6_WEB_DASHBOARD=true
          export K6_WEB_DASHBOARD_EXPORT=report.html

          # Executa o script K6 com o handleSummary e redireciona logs
          k6 run --vus 2 --duration 30s --out json=output.json aula31.js | tee logs/k6_test.log

          echo "Execução do K6 finalizada."

          # Gera o relatório HTML via handleSummary
          echo "Gerando o relatório HTML via handleSummary..."
          k6 run --out json=output.json --summary-trend-stats "avg,p(90),p(95),max" aula31.js | tee -a logs/k6_test.log

          echo "Ambos os relatórios foram gerados."

      - name: Step 3 - Create Report Directory
        run: |
          mkdir -p report
          mv report.html report || echo "report.html not found"  # Move o relatório HTML gerado ou exibe mensagem
          mv output.json report || echo "output.json not found"  # Move o arquivo JSON de saída para o diretório de relatório
          mv logs/k6_test.log report || echo "k6_test.log not found"  # Move os logs para o diretório de relatório

      - name: Step 4 - Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: relatorio de testes de performance
          path: report  # Agora inclui todos os arquivos gerados (report.html, output.json e k6_test.log)

      - name: Step 5 - Publish Report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: report

